{"name": "Проверка невозможности получить заказ, если отправить несуществующий номер. Получаем код 404 и сообщение: Заказ не найден", "status": "passed", "start": 1719232059340, "stop": 1719232059493, "uuid": "068cbe7e-e398-4902-b1c9-843a6d151dc9", "historyId": "4ecb510039edc31aaca2cdf68bdfdb93", "testCaseId": "4ecb510039edc31aaca2cdf68bdfdb93", "fullName": "tests.test_order_by_number.TestOrderByNumber#test_get_order_with_incorrect_number", "labels": [{"name": "story", "value": "Тесты получения заказов по номеру"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_by_number"}, {"name": "subSuite", "value": "TestOrderByNumber"}, {"name": "host", "value": "DESKTOP-7KB2K2E"}, {"name": "thread", "value": "15328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_by_number"}]}