{"name": "Проверка невозможности создании курьера с существующим логином. Получаем ошибку 409", "status": "passed", "steps": [{"name": "Генерируем рандомную строку", "status": "passed", "parameters": [{"name": "length", "value": "10"}], "start": 1719232033584, "stop": 1719232033584}, {"name": "Генерируем рандомную строку", "status": "passed", "parameters": [{"name": "length", "value": "10"}], "start": 1719232033584, "stop": 1719232033584}], "start": 1719232033584, "stop": 1719232033658, "uuid": "f64e2a2e-24f5-4270-b911-33defa022002", "historyId": "d7ce461722371cac25f699d69b92318e", "testCaseId": "d7ce461722371cac25f699d69b92318e", "fullName": "tests.test_courier_creating.TestCourierCreating#test_courier_creating_using_same_login", "labels": [{"name": "story", "value": "Тесты создания курьеров"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creating"}, {"name": "subSuite", "value": "TestCourierCreating"}, {"name": "host", "value": "DESKTOP-7KB2K2E"}, {"name": "thread", "value": "15328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creating"}]}